destination: ./public

permalink: pretty

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - vendor
  - bin

markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code
    - no_intraemphasis

sitemap:
  url: http://andre.arko.net
