destination: ./public
auto:        false
lsi:         false
server_port: 4444
pygments:    true
markdown:    redcarpet
permalink:   pretty
exclude:
  - Thorfile
  - Gemfile
  - Gemfile.lock
  - vendor
redcarpet:
  extensions:
    - fenced_code
    - no_intraemphasis
    - smart
