destination: ./public

permalink:   pretty

exclude:
  - Thorfile
  - Gemfile
  - Gemfile.lock
  - vendor
  - bin

markdown:    redcarpet
redcarpet:
  extensions:
    - fenced_code
    - no_intraemphasis
